// The deploy pipeline: agent config in, live Convex deployment out.
//
//   materialize  copy apps/agent + packages/backend templates into a scratch
//                workspace, apply the config (model, instructions, tools,
//                schedule, crons)
//   build        `eve build` the agent, vendor the bundle into the backend copy
//   provision    create a fresh Convex project (or reuse on redeploy) and push
//   configure    set deployment env vars (world secret, queue namespace, keys)
//   bundle       upload the eve bundle into Convex storage (runner hot-swaps)
//   web          vite-build the dashboard against the new deployment + upload
//   verify       runner probe + static site check
//
// Uses the Convex CLI (authenticated via ~/.convex) for provisioning/pushes —
// the same operations the Management API exposes for platform accounts.

import { mkdir, rm, readFile, symlink, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { childEnv, randHex, run } from "./util.mjs";

/** Catalog tools that exist as files in the template: off → delete the file. */
const TOOL_FILES = {
  saveNote: "save_note.ts",
  listNotes: "list_notes.ts",
  clearNotes: "clear_notes.ts",
  workflowStats: "workflow_stats.ts",
};

/**
 * eve framework tools (enabled by default inside eve): off → write a
 * disableTool() override at the tool's slug.
 */
const FRAMEWORK_TOOL_FILES = {
  webFetch: "web_fetch.ts",
  webSearch: "web_search.ts",
};

const DISABLE_TOOL_SOURCE = `import { disableTool } from "eve/tools";

// Generated by the agent builder — this framework tool is toggled off.
export default disableTool();
`;

/**
 * Assistant capability groups: off → delete the listed template files. Each
 * group's Convex tables stay in the deployment schema (harmlessly empty).
 */
const CAPABILITY_FILES = {
  memory: [
    "agent/tools/remember.ts",
    "agent/tools/forget.ts",
    "agent/tools/search_memory.ts",
    "agent/tools/list_memories.ts",
    "agent/instructions/30-memory.ts",
    "agent/schedules/memory-consolidation.md",
  ],
  skills: [
    "agent/tools/create_skill.ts",
    "agent/tools/delete_skill.ts",
    "agent/instructions/40-skills.ts",
  ],
  reminders: [
    "agent/tools/create_reminder.ts",
    "agent/tools/list_reminders.ts",
    "agent/tools/cancel_reminder.ts",
    "agent/schedules/reminders.ts",
  ],
  eventTriggers: [
    "agent/tools/create_webhook.ts",
    "agent/tools/list_webhooks.ts",
    "agent/tools/delete_webhook.ts",
    "agent/channels/hooks.ts",
  ],
  receipts: [
    "agent/tools/log_receipt.ts",
    "agent/tools/query_receipts.ts",
    "agent/tools/spending_summary.ts",
    "agent/tools/delete_receipt.ts",
  ],
  extras: ["agent/tools/get_weather.ts", "agent/tools/roll_dice.ts"],
  delegation: ["agent/tools/workflow.ts"],
};

// Queue namespace is derived from the agent package name ("agent"), which the
// workspace copy keeps — so it is identical for every deployed agent. Each
// agent has its own deployment, so namespaces never collide across agents.
const QUEUE_NAMESPACE = "eve" + Buffer.from("agent", "utf8").toString("hex");

function agentTs(model) {
  return `import type { ModelMessage } from "ai";
import { defineAgent, defineDynamic } from "eve";

// Generated by the agent builder — do not edit by hand.

const DEFAULT_MODEL = ${JSON.stringify(model)};

const MODEL_ID_PATTERN = /^[\\w.-]+\\/[\\w.:-]+$/;

const CLIENT_CONTEXT_PREFIX = "Client context:\\n";

// The web chat attaches { eveWebModel } as one-turn clientContext, which the
// eve channel delivers as a user-role message "Client context:\\n<json>".
// Scan the visible conversation from the end for that marker; sessions
// without one (schedules, webhooks, Telegram) run on the configured default.
function requestedModel(messages: readonly ModelMessage[]): string | null {
  for (let index = messages.length - 1; index >= 0; index--) {
    const { content } = messages[index];
    const texts =
      typeof content === "string"
        ? [content]
        : content.map((part) => ("text" in part && typeof part.text === "string" ? part.text : ""));
    for (const text of texts) {
      const model = parseModelMarker(text);
      if (model !== null) return model;
    }
  }
  return null;
}

function parseModelMarker(text: string): string | null {
  if (!text.startsWith(CLIENT_CONTEXT_PREFIX)) return null;
  try {
    const parsed: unknown = JSON.parse(text.slice(CLIENT_CONTEXT_PREFIX.length));
    if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) return null;
    const model = (parsed as Record<string, unknown>).eveWebModel;
    return typeof model === "string" && MODEL_ID_PATTERN.test(model) ? model : null;
  } catch {
    return null;
  }
}

export default defineAgent({
  // step.started, not turn.started: in eve 0.22 the step-level dispatch is
  // the one whose ctx.messages includes the current turn's just-injected
  // "Client context:" message (turn.started sees only prior conversation).
  model: defineDynamic({
    fallback: DEFAULT_MODEL,
    events: {
      "step.started": (_event, ctx) => requestedModel(ctx.messages),
    },
  }),
  experimental: {
    workflow: {
      world: "world-convex",
    },
  },
  build: {
    externalDependencies: ["world-convex"],
  },
});
`;
}

function heartbeatMd(schedule) {
  return `---
cron: "${schedule.cron.trim()}"
---

${schedule.prompt.trim()}
`;
}

function cronsTs(schedule, { reminders, memory }) {
  const heartbeat = schedule.enabled
    ? `
// eve markdown schedule (agent/schedules/heartbeat.md) — the Convex cron
// mirrors the frontmatter so the tick fires inside Convex.
crons.cron(
  "eve heartbeat schedule",
  ${JSON.stringify(schedule.cron.trim())},
  internal.runner.schedule.heartbeat,
  {},
);
`
    : `
// No agent schedule configured for this deployment.
`;

  const remindersCron = reminders
    ? `
// eve reminders schedule (agent/schedules/reminders.ts) — every minute,
// claims due reminders and delivers proactive sessions.
crons.interval(
  "eve reminders schedule",
  { minutes: 1 },
  internal.runner.schedule.reminders,
  {},
);
`
    : "";

  const memoryCron = memory
    ? `
// eve memory-consolidation schedule (agent/schedules/memory-consolidation.md)
// — nightly, matching its "15 8 * * *" cron.
crons.daily(
  "eve memory consolidation schedule",
  { hourUTC: 8, minuteUTC: 15 },
  internal.runner.schedule.memoryConsolidation,
  {},
);
`
    : "";

  return `import { cronJobs } from "convex/server";
import { internal } from "./_generated/api";

// Generated by the agent builder — do not edit by hand.
const crons = cronJobs();

// Lease recovery: a crashed worker leaves jobs in \`claimed\` past their lease.
crons.interval(
  "requeue expired queue leases",
  { minutes: 1 },
  internal.world.queue.requeueExpired,
  {},
);

// Convex-mode safety net: wake the runner if a scheduled tick was lost.
crons.interval(
  "sweep due queue jobs",
  { minutes: 1 },
  internal.world.queue.sweepDue,
  {},
);
${heartbeat}${remindersCron}${memoryCron}
// Keep the dead-letter set bounded.
crons.daily(
  "cleanup dead queue jobs",
  { hourUTC: 4, minuteUTC: 0 },
  internal.world.queue.cleanupDead,
  {},
);

// Drop stale BYOK session keys so visitor credentials don't accumulate.
crons.daily(
  "cleanup stale session keys",
  { hourUTC: 4, minuteUTC: 30 },
  internal.keys.cleanup,
  {},
);

export default crons;
`;
}

async function rsync(from, to, excludes, log) {
  const args = ["-a", ...excludes.flatMap((e) => ["--exclude", e]), `${from}/`, `${to}/`];
  await run("rsync", args, { log, label: "rsync", timeoutMs: 60_000 });
}

function parseEnvLocal(text) {
  const m = text.match(/^CONVEX_DEPLOYMENT=dev:([a-z0-9-]+)/m);
  if (!m) throw new Error("Could not parse CONVEX_DEPLOYMENT from .env.local");
  return m[1];
}

/**
 * @param input  { config, aiGatewayApiKey?, existing? } — the worker `claim`
 *               payload (or a CLI-provided equivalent).
 * @param opts   { repoRoot, team, workRoot, log, setStep }
 */
export async function deployAgent(input, opts) {
  const {
    config,
    aiGatewayApiKey,
    telegramBotToken,
    composioApiKey,
    convexDeployKey,
    existing,
  } = input;
  const priorWebhookSecret = input.webhookSecret;
  const { repoRoot, team, workRoot, log } = opts;
  const setStep = opts.setStep ?? (() => {});

  const ws = join(workRoot, `${config.slug}-${Date.now().toString(36)}`);
  const agentDir = join(ws, "agent");
  const backendDir = join(ws, "backend");

  // ---- materialize ---------------------------------------------------------
  await setStep("materialize");
  log(`Workspace: ${ws}`);
  await mkdir(agentDir, { recursive: true });
  await mkdir(backendDir, { recursive: true });

  await rsync(
    join(repoRoot, "apps/agent"),
    agentDir,
    ["/node_modules", "/.output", "/.vercel", "/.eve", "/.workflow-data", ".env*"],
    log,
  );
  await rsync(
    join(repoRoot, "packages/backend"),
    backendDir,
    ["/node_modules", "/eve-runtime", "/.workflow-data", ".env*"],
    log,
  );

  // Symlinked node_modules: pnpm's layout resolves through the real path, so
  // a single dir symlink gives the workspace the full dependency tree.
  await symlink(join(repoRoot, "apps/agent/node_modules"), join(agentDir, "node_modules"), "dir");
  await symlink(
    join(repoRoot, "packages/backend/node_modules"),
    join(backendDir, "node_modules"),
    "dir",
  );

  await writeFile(join(agentDir, "agent/agent.ts"), agentTs(config.model));
  await writeFile(
    join(agentDir, "agent/instructions.md"),
    config.instructions.trim() + "\n",
  );

  for (const [key, file] of Object.entries(TOOL_FILES)) {
    if (!config.tools[key]) {
      await rm(join(agentDir, "agent/tools", file), { force: true });
      log(`tool disabled: ${file}`);
    }
  }
  for (const [key, file] of Object.entries(FRAMEWORK_TOOL_FILES)) {
    if (config.tools[key] === false) {
      await writeFile(join(agentDir, "agent/tools", file), DISABLE_TOOL_SOURCE);
      log(`framework tool disabled: ${file}`);
    }
  }

  // Capability groups: off → delete the group's template files. (The
  // telegram + proactive channel modules always stay: reminders and hooks
  // import them, and both are inert without their env vars / callers.)
  for (const [key, files] of Object.entries(CAPABILITY_FILES)) {
    if (config.tools[key] === false) {
      for (const file of files) {
        await rm(join(agentDir, file), { force: true });
      }
      log(`capability disabled: ${key}`);
    }
  }

  const webhookEnabled = config.channels?.webhook?.enabled === true;
  if (!webhookEnabled) {
    // Without the module the bundle registers no webhook route and the
    // Convex endpoint answers 404.
    await rm(join(agentDir, "agent/channels/webhook.ts"), { force: true });
    log("webhook channel disabled");
  } else {
    log("webhook channel enabled");
  }

  const telegramEnabled =
    config.channels?.telegram?.enabled === true && Boolean(telegramBotToken);
  log(
    telegramEnabled
      ? "telegram channel enabled"
      : config.channels?.telegram?.enabled === true
        ? "telegram channel requested but no bot token — disabled"
        : "telegram channel disabled",
  );

  const composioEnabled = Boolean(composioApiKey);
  if (!composioEnabled) {
    await rm(join(agentDir, "agent/connections/composio.ts"), { force: true });
    log("composio connection disabled (no API key)");
  } else {
    log("composio connection enabled");
  }

  const schedulesDir = join(agentDir, "agent/schedules");
  await rm(join(schedulesDir, "heartbeat.md"), { force: true });
  if (config.schedule.enabled) {
    await mkdir(schedulesDir, { recursive: true });
    await writeFile(join(schedulesDir, "heartbeat.md"), heartbeatMd(config.schedule));
    log(`schedule enabled: ${config.schedule.cron}`);
  } else {
    log("schedule disabled");
  }

  await writeFile(
    join(backendDir, "convex/crons.ts"),
    cronsTs(config.schedule, {
      reminders: config.tools.reminders !== false,
      memory: config.tools.memory !== false,
    }),
  );

  // ---- build ---------------------------------------------------------------
  await setStep("build");
  const eveBin = join(agentDir, "node_modules/.bin/eve");
  await run(eveBin, ["build"], {
    cwd: agentDir,
    log,
    label: "eve build",
    timeoutMs: 10 * 60_000,
  });

  const serverDir = join(agentDir, ".output/server");
  if (!existsSync(join(serverDir, "_libs/eve.mjs"))) {
    throw new Error("eve build produced no _libs/eve.mjs — build output incomplete");
  }
  // vendor-eve.mjs also generates entry.mjs (stable names for the minified
  // per-build export aliases) — the Convex runner imports only entry.mjs.
  await run(process.execPath, ["scripts/vendor-eve.mjs", serverDir], {
    cwd: backendDir,
    log,
    label: "vendor bundle",
    timeoutMs: 60_000,
  });

  // ---- provision -----------------------------------------------------------
  await setStep("provision");
  const convexBin = join(backendDir, "node_modules/.bin/convex");
  // Bring-your-own-Convex: the deploy key selects the target deployment for
  // every CLI call, so the user's agent lives in their own Convex account
  // (no project is created in the operator's team).
  const convexCliEnv = convexDeployKey
    ? childEnv({ CONVEX_DEPLOY_KEY: convexDeployKey })
    : undefined;
  let projectSlug;
  let deploymentName;

  if (convexDeployKey) {
    const match = convexDeployKey.match(/^(?:prod|dev):([a-z0-9-]+)\|/);
    if (!match) {
      throw new Error(
        'Convex deploy key is not a deployment deploy key (expected "prod:<deployment-name>|…" from the project\'s Settings → Deploy key)',
      );
    }
    deploymentName = match[1];
    projectSlug = existing?.projectSlug ?? config.slug;
    log(`Deploying to user-owned Convex deployment ${deploymentName} (deploy key)`);
    await run(convexBin, ["deploy", "--yes"], {
      cwd: backendDir,
      env: convexCliEnv,
      log,
      label: "convex deploy",
      timeoutMs: 10 * 60_000,
    });
  } else if (existing) {
    projectSlug = existing.projectSlug;
    deploymentName = existing.deploymentName;
    log(`Redeploying to existing deployment ${deploymentName}`);
    await writeFile(
      join(backendDir, ".env.local"),
      `CONVEX_DEPLOYMENT=dev:${deploymentName}\n`,
    );
    await run(convexBin, ["dev", "--once"], {
      cwd: backendDir,
      log,
      label: "convex push",
      timeoutMs: 10 * 60_000,
    });
  } else {
    projectSlug = `${config.slug}-${randHex(2)}`;
    log(`Creating Convex project "${projectSlug}" in team "${team}"`);
    await run(
      convexBin,
      [
        "dev",
        "--once",
        "--configure",
        "new",
        "--team",
        team,
        "--project",
        projectSlug,
        "--dev-deployment",
        "cloud",
      ],
      { cwd: backendDir, log, label: "convex provision", timeoutMs: 10 * 60_000 },
    );
    deploymentName = parseEnvLocal(
      await readFile(join(backendDir, ".env.local"), "utf8"),
    );
  }

  const deploymentUrl = `https://${deploymentName}.convex.cloud`;
  const siteUrl = `https://${deploymentName}.convex.site`;
  log(`Deployment: ${deploymentName} (${deploymentUrl})`);

  // ---- configure -----------------------------------------------------------
  await setStep("configure");
  const { output: envListOut } = await run(convexBin, ["env", "list"], {
    cwd: backendDir,
    env: convexCliEnv,
    log: () => {},
    label: "convex env list",
    timeoutMs: 60_000,
  });
  const remoteEnv = new Map(
    envListOut
      .split("\n")
      .map((l) => l.match(/^([A-Z0-9_]+)=(.*)$/))
      .filter(Boolean)
      .map((m) => [m[1], m[2]]),
  );

  const worldSecret = remoteEnv.get("WORLD_SERVICE_SECRET") ?? randHex(24);
  // Stable across redeploys: builder record > deployment env > fresh.
  const webhookSecret = webhookEnabled
    ? (priorWebhookSecret ??
      remoteEnv.get("WEBHOOK_CHANNEL_SECRET") ??
      `whsec_${randHex(16)}`)
    : undefined;

  // Stable across redeploys, like the webhook secret.
  const telegramWebhookSecretToken = telegramEnabled
    ? (remoteEnv.get("TELEGRAM_WEBHOOK_SECRET_TOKEN") ?? `tgsec_${randHex(16)}`)
    : undefined;

  const envSets = {
    WORLD_SERVICE_SECRET: worldSecret,
    WORLD_EXECUTION_MODE: "convex",
    WORLD_CONVEX_DISABLE_PUMP: "1",
    CONVEX_URL: deploymentUrl,
    WORKFLOW_QUEUE_NAMESPACE: QUEUE_NAMESPACE,
    AGENT_DEFAULT_TIMEZONE: config.timezone ?? "UTC",
  };
  if (aiGatewayApiKey) {
    envSets.AI_GATEWAY_API_KEY = aiGatewayApiKey;
    // Explicit opt-in: web chat bills the deployment key and the UI skips
    // the visitor-key dialog. Deployments holding a key only for schedules
    // (the adam demo) never set this and stay BYOK.
    envSets.CHAT_USE_DEPLOYMENT_KEY = "1";
  }
  if (webhookSecret) envSets.WEBHOOK_CHANNEL_SECRET = webhookSecret;
  if (composioEnabled) envSets.COMPOSIO_API_KEY = composioApiKey;
  if (telegramEnabled) {
    envSets.TELEGRAM_BOT_TOKEN = telegramBotToken;
    envSets.TELEGRAM_WEBHOOK_SECRET_TOKEN = telegramWebhookSecretToken;
    // Telegram's inbound route can't surface session ids, so those sessions
    // run on the deployment credential via the runner's key fallback.
    envSets.RUNNER_SYSTEM_KEY_FALLBACK = "1";
    const allowed = (config.channels?.telegram?.allowedUserIds ?? "").trim();
    if (allowed) envSets.TELEGRAM_ALLOWED_USER_IDS = allowed;
  }

  for (const [name, value] of Object.entries(envSets)) {
    await run(convexBin, ["env", "set", name, value], {
      cwd: backendDir,
      env: convexCliEnv,
      log: (l) => log(l.replace(value, "***")),
      label: `env set ${name}`,
      timeoutMs: 60_000,
    });
  }
  const envRemovals = [];
  if (!webhookEnabled) envRemovals.push("WEBHOOK_CHANNEL_SECRET");
  if (!composioEnabled) envRemovals.push("COMPOSIO_API_KEY");
  if (!telegramEnabled) {
    envRemovals.push(
      "TELEGRAM_BOT_TOKEN",
      "TELEGRAM_WEBHOOK_SECRET_TOKEN",
      "TELEGRAM_ALLOWED_USER_IDS",
      "RUNNER_SYSTEM_KEY_FALLBACK",
    );
  } else if (!(config.channels?.telegram?.allowedUserIds ?? "").trim()) {
    envRemovals.push("TELEGRAM_ALLOWED_USER_IDS");
  }
  for (const name of envRemovals) {
    if (!remoteEnv.has(name)) continue;
    await run(convexBin, ["env", "remove", name], {
      cwd: backendDir,
      env: convexCliEnv,
      log,
      label: `env remove ${name}`,
      timeoutMs: 60_000,
    });
  }
  log(
    aiGatewayApiKey
      ? "deployment credential set (AI_GATEWAY_API_KEY + CHAT_USE_DEPLOYMENT_KEY) — web chat bills it"
      : "no deployment credential — chat will require a visitor key (builder should have blocked deploy)",
  );
  if ((webhookEnabled || telegramEnabled) && !aiGatewayApiKey) {
    log(
      "warning: webhook/telegram channels are enabled but no AI Gateway key is configured — their turns will fail until one is added",
    );
  }

  // Register the deployment's Telegram webhook (or drop a stale one).
  if (telegramEnabled) {
    const tgRes = await fetch(
      `https://api.telegram.org/bot${telegramBotToken}/setWebhook`,
      {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          url: `${siteUrl}/channels/telegram`,
          secret_token: telegramWebhookSecretToken,
          allowed_updates: ["message", "callback_query"],
        }),
      },
    );
    const tgJson = await tgRes.json().catch(() => ({}));
    if (tgJson.ok !== true) {
      throw new Error(
        `Telegram setWebhook failed: ${JSON.stringify(tgJson).slice(0, 300)}`,
      );
    }
    log(`telegram webhook registered → ${siteUrl}/channels/telegram`);
  }

  // ---- bundle --------------------------------------------------------------
  await setStep("bundle");
  await run(process.execPath, ["scripts/upload-bundle.mjs"], {
    cwd: backendDir,
    env: childEnv({ CONVEX_URL: deploymentUrl, WORLD_SERVICE_SECRET: worldSecret }),
    log,
    label: "upload bundle",
    timeoutMs: 5 * 60_000,
  });

  // ---- web -----------------------------------------------------------------
  await setStep("web");
  const webDist = join(ws, "web-dist");
  const viteBin = join(repoRoot, "apps/web/node_modules/.bin/vite");
  await run(viteBin, ["build", "--outDir", webDist, "--emptyOutDir"], {
    cwd: join(repoRoot, "apps/web"),
    // VITE_AGENT_* brand the dashboard as this agent's own app (name in the
    // header/landing, model chip, webhook card when the channel is on).
    env: childEnv({
      VITE_CONVEX_URL: deploymentUrl,
      VITE_AGENT_NAME: config.name,
      VITE_AGENT_MODEL: config.model,
      VITE_WEBHOOK_ENABLED: webhookEnabled ? "1" : "0",
    }),
    log,
    label: "vite build",
    timeoutMs: 5 * 60_000,
  });
  const hostingBin = join(backendDir, "node_modules/.bin/static-hosting");
  await run(hostingBin, ["upload", "--dist", webDist], {
    cwd: backendDir,
    env: convexCliEnv ?? childEnv({ CONVEX_DEPLOYMENT: `dev:${deploymentName}` }),
    log,
    label: "static hosting upload",
    timeoutMs: 5 * 60_000,
  });

  // ---- verify --------------------------------------------------------------
  await setStep("verify");
  const { output: probeOut } = await run(convexBin, ["run", "runner/probe:probe"], {
    cwd: backendDir,
    env: convexCliEnv,
    log,
    label: "probe",
    timeoutMs: 3 * 60_000,
  });
  const jsonStart = probeOut.indexOf("{");
  if (jsonStart === -1) throw new Error("probe returned no JSON");
  const probe = JSON.parse(probeOut.slice(jsonStart));
  if (probe.worldInstalled !== true) {
    throw new Error(`probe failed: ${JSON.stringify(probe)}`);
  }
  const bundleVersion = String(probe.version ?? "unknown");

  const siteRes = await fetch(siteUrl);
  log(`site check: GET ${siteUrl} → ${siteRes.status}`);
  if (!siteRes.ok) throw new Error(`static site returned ${siteRes.status}`);

  if (webhookEnabled) {
    // Wrong secret must 401: proves the route is mounted, the bundle has the
    // channel, and secret enforcement is on.
    const whRes = await fetch(`${siteUrl}/channels/webhook`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-webhook-secret": "probe-wrong-secret",
      },
      body: JSON.stringify({ message: "probe" }),
    });
    log(`webhook check: POST ${siteUrl}/channels/webhook → ${whRes.status}`);
    if (whRes.status !== 401) {
      throw new Error(
        `webhook channel probe expected 401, got ${whRes.status}`,
      );
    }
  }

  // Success: scrap the workspace (kept on failure for debugging).
  await rm(ws, { recursive: true, force: true });

  return {
    projectSlug,
    deploymentName,
    deploymentUrl,
    dashboardUrl: siteUrl,
    bundleVersion,
    webhookSecret,
  };
}

/**
 * Env vars scrubbed from a deployment on delete. Removing the AI key stops
 * all model spend (scheduled heartbeats fail fast at the gateway call) and
 * removing the webhook secret makes the channel endpoint 401 everything.
 */
const TEARDOWN_ENV_VARS = [
  "AI_GATEWAY_API_KEY",
  "CHAT_USE_DEPLOYMENT_KEY",
  "VERCEL_OIDC_TOKEN",
  "WEBHOOK_CHANNEL_SECRET",
  "TELEGRAM_BOT_TOKEN",
  "TELEGRAM_WEBHOOK_SECRET_TOKEN",
  "COMPOSIO_API_KEY",
];

/**
 * Tear down a deleted agent's deployment as far as the CLI allows: scrub its
 * credentials so the orphaned project can't spend tokens or serve webhooks.
 * The Convex CLI has no project-delete command, so the project itself stays
 * until removed in the Convex dashboard (link logged below).
 *
 * @param job  { name, projectSlug?, deploymentName?, convexDeployKey? } —
 *             worker `claim` payload
 * @param opts { repoRoot, log, setStep }
 */
export async function teardownAgent(job, opts) {
  const { repoRoot, log } = opts;
  const setStep = opts.setStep ?? (() => {});

  await setStep("scrub");
  if (!job.deploymentName) {
    log("no deployment recorded — nothing to scrub");
    return;
  }

  // The repo's backend package has the CLI installed; deployment selection
  // comes from CONVEX_DEPLOYMENT (process env wins over any .env.local).
  const backendDir = join(repoRoot, "packages/backend");
  const convexBin = join(backendDir, "node_modules/.bin/convex");
  // Bring-your-own-Convex deployments are reached via their deploy key; the
  // operator's account has no access to them.
  const env = job.convexDeployKey
    ? childEnv({ CONVEX_DEPLOY_KEY: job.convexDeployKey })
    : childEnv({ CONVEX_DEPLOYMENT: `dev:${job.deploymentName}` });

  log(`Scrubbing credentials on ${job.deploymentName}`);
  // List first: proves the deployment is reachable with our credentials (a
  // revoked deploy key must fail the teardown, not silently skip the scrub),
  // and tells us which vars actually need removing.
  let listOut;
  try {
    ({ output: listOut } = await run(convexBin, ["env", "list"], {
      cwd: backendDir,
      env,
      log: () => {},
      label: "env list",
      timeoutMs: 60_000,
    }));
  } catch (err) {
    throw new Error(
      `cannot reach deployment ${job.deploymentName} to scrub credentials: ${err.message}`,
    );
  }
  const present = new Set(
    listOut
      .split("\n")
      .map((l) => l.match(/^([A-Z0-9_]+)=/)?.[1])
      .filter(Boolean),
  );
  for (const name of TEARDOWN_ENV_VARS) {
    if (!present.has(name)) continue;
    await run(convexBin, ["env", "remove", name], {
      cwd: backendDir,
      env,
      log,
      label: `env remove ${name}`,
      timeoutMs: 60_000,
    });
  }

  log(`✓ credentials scrubbed — agent can no longer spend tokens`);
  log(
    `note: the Convex project "${job.projectSlug ?? job.deploymentName}" still exists; ` +
      `delete it from the dashboard for full removal: ` +
      `https://dashboard.convex.dev/d/${job.deploymentName}/settings`,
  );
}
