// Vendors the compiled eve server bundle (apps/agent/.output/server) into
// packages/backend/eve-runtime/bundle so Convex "use node" actions can import
// the agent + workflow runtime and execute it inside Convex.
//
// Run `eve build` in apps/agent first, then `pnpm vendor:eve` here (the root
// `pnpm build` pipeline chains both). An alternate build output dir may be
// passed as argv[2] (used by the platform deploy pipeline's workspaces).
//
// index.mjs is intentionally excluded from the copy: importing it would start
// the Nitro HTTP server. But it IS parsed: eve's rolldown pass assigns
// minified export names in _libs/eve.mjs that are NOT stable across builds
// (`B as POST` one build, `z as POST` the next). index.mjs imports them under
// their canonical local names, so we recover the mapping from its import
// statement and emit an entry.mjs with stable re-exports. The Convex runner
// imports only entry.mjs.

import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const backendRoot = resolve(here, "..");
const serverDir = process.argv[2]
  ? resolve(process.argv[2])
  : resolve(backendRoot, "../../apps/agent/.output/server");
const outDir = join(backendRoot, "eve-runtime", "bundle");

if (!existsSync(join(serverDir, "_libs", "eve.mjs"))) {
  console.error(
    `Missing ${join(serverDir, "_libs/eve.mjs")}. Run \`eve build\` in the agent app first.`,
  );
  process.exit(1);
}

/** Parse `import { z as POST, W as Gg, … } from "./_libs/eve.mjs"` → Map(local → exported). */
function parseEveImports(source, specifier) {
  const re = new RegExp(
    `import\\s*\\{([^}]*)\\}\\s*from\\s*["']${specifier.replace(/[./]/g, "\\$&")}["']`,
  );
  const match = source.match(re);
  if (!match) return null;
  const map = new Map();
  for (const piece of match[1].split(",")) {
    const part = piece.trim();
    if (!part) continue;
    const asMatch = part.match(/^([\w$]+)\s+as\s+([\w$]+)$/);
    if (asMatch) map.set(asMatch[2], asMatch[1]);
    else map.set(part, part);
  }
  return map;
}

function buildEntrySource() {
  const indexSource = readFileSync(join(serverDir, "index.mjs"), "utf8");
  const imports = parseEveImports(indexSource, "./_libs/eve.mjs");
  if (!imports) {
    throw new Error("index.mjs has no import from ./_libs/eve.mjs — eve output layout changed");
  }

  const exports = new Map();

  // POST (flow route handler) and dispatchChannelRequest keep their real
  // names as import locals in index.mjs.
  for (const name of ["POST", "dispatchChannelRequest"]) {
    const exported = imports.get(name);
    if (!exported) throw new Error(`index.mjs does not import ${name} from _libs/eve.mjs`);
    exports.set(name, exported);
  }

  // getWorld is imported under a minified local, but index.mjs assigns its
  // result to the unminified __eveWorkflowWorld — recover it from that call.
  const worldMatch = indexSource.match(/__eveWorkflowWorld\s*=\s*await\s+([\w$]+)\s*\(/);
  if (!worldMatch) throw new Error("could not locate __eveWorkflowWorld getter in index.mjs");
  const worldExported = imports.get(worldMatch[1]);
  if (!worldExported) {
    throw new Error(`world getter ${worldMatch[1]} not found in eve.mjs import map`);
  }
  exports.set("getWorld", worldExported);

  // dispatchScheduleTask only exists when the agent defines schedules; the
  // virtual schedule module imports it by name.
  const schedulePath = join(serverDir, "_virtual", "eve.schedule.mjs");
  if (existsSync(schedulePath)) {
    const scheduleImports = parseEveImports(
      readFileSync(schedulePath, "utf8"),
      "../_libs/eve.mjs",
    );
    const exported = scheduleImports?.get("dispatchScheduleTask");
    if (!exported) {
      throw new Error("eve.schedule.mjs does not import dispatchScheduleTask");
    }
    exports.set("dispatchScheduleTask", exported);
  }

  const specifiers = [...exports.entries()]
    .map(([name, exported]) => `  ${exported} as ${name},`)
    .join("\n");
  return `// Generated by scripts/vendor-eve.mjs — stable names for the minified
// per-build export aliases of _libs/eve.mjs. The Convex runner imports this
// file only.
export {
${specifiers}
} from "./_libs/eve.mjs";
`;
}

const entrySource = buildEntrySource();

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

for (const entry of ["_libs", "_virtual", "_runtime.mjs"]) {
  const src = join(serverDir, entry);
  if (!existsSync(src)) continue;
  cpSync(src, join(outDir, entry), { recursive: true });
}
writeFileSync(join(outDir, "entry.mjs"), entrySource);

const size = statSync(join(outDir, "_libs", "eve.mjs")).size;
console.log(
  `Vendored eve bundle → ${outDir} (eve.mjs ${(size / 1024 / 1024).toFixed(1)} MB)`,
);
console.log(entrySource.split("\n").filter((l) => l.includes(" as ")).join("\n"));
